"""The Data Analyst Agent (Phase 2).

Flow:

    context
        -> LLM writes SQL via tool call OR plain-text SQL
        -> Python validates + executes
        -> retry once on SQL error
        -> result converted to an AUTHORITATIVE block
        -> LLM writes the answer
        -> JSON/Pydantic validation
        -> every number in the answer is verified against the result
        -> repair once
        -> deterministic fallback
"""

from __future__ import annotations

import logging
import time
from typing import Any, Optional

import ollama
from pydantic import ValidationError

from agent.context import build_context
from agent.grounding import ground_result, verify_answer
from agent.prompts import (
    INTERPRET_INSTRUCTIONS,
    REPAIR_INSTRUCTIONS,
    SYSTEM_PROMPT,
)
from agent.tools import (
    EXECUTE_SQL_TOOL,
    execute_sql,
    extract_sql_from_text,
)
from config import Settings, get_settings
from models.response import AnalystResponse, LLMAnswer, ToolResult


log = logging.getLogger(__name__)


class DataAnalystAgent:

    def __init__(
        self,
        client: Any = None,
        settings: Optional[Settings] = None,
    ):
        self.settings = settings or get_settings()
        self.client = client or ollama.Client(
            host=self.settings.ollama_host
        )

    # ------------------------------------------------------------------
    # Public
    # ------------------------------------------------------------------

    def run(
        self,
        question: str,
        history: Optional[list[dict]] = None,
    ) -> AnalystResponse:

        t0 = time.perf_counter()

        timings = {
            "llm_sql_ms": 0.0,
            "sql_exec_ms": 0.0,
            "llm_answer_ms": 0.0,
        }

        try:
            resp = self._run(
                question,
                history or [],
                timings,
            )

        except Exception as exc:
            log.exception("Agent failed")

            resp = AnalystResponse(
                answer=f"Something went wrong while answering: {exc}",
                status="error",
                error=str(exc),
            )

        timings["total_ms"] = (
            time.perf_counter() - t0
        ) * 1000

        resp.timings_ms = {
            k: round(v, 1)
            for k, v in timings.items()
        }

        return resp

    # ------------------------------------------------------------------
    # Ollama chat wrapper
    # ------------------------------------------------------------------

    def _chat(
        self,
        messages: list[dict],
        timing_key: str,
        timings: dict,
        **kwargs,
    ):

        start = time.perf_counter()

        out = self.client.chat(
            model=self.settings.llm_model,
            messages=messages,
            options={
                "temperature": self.settings.llm_temperature,
                "num_ctx": self.settings.llm_num_ctx,
            },
            **kwargs,
        )

        timings[timing_key] += (
            time.perf_counter() - start
        ) * 1000

        return out

    # ------------------------------------------------------------------
    # Main agent flow
    # ------------------------------------------------------------------

    def _run(
        self,
        question: str,
        history: list[dict],
        timings: dict,
    ) -> AnalystResponse:

        s = self.settings

        # --------------------------------------------------------------
        # Build context
        # --------------------------------------------------------------

        ctx = build_context(question)

        system = SYSTEM_PROMPT.replace(
            "{data_window}",
            ctx.data_window,
        ).replace(
            "{context}",
            ctx.text,
        )

        messages: list[dict] = [
            {
                "role": "system",
                "content": system,
            },
            *history,
            {
                "role": "user",
                "content": question,
            },
        ]

        # --------------------------------------------------------------
        # Step 1:
        #
        # LLM -> SQL
        #
        # Supports:
        #
        # 1. Native function calling
        #
        #    tool_calls = [...]
        #
        # 2. Plain text generated by local models
        #
        #    SQL: SELECT ...
        #
        # --------------------------------------------------------------

        result: Optional[ToolResult] = None
        attempts = 0

        while attempts < s.max_sql_attempts:

            attempts += 1

            reply = self._chat(
                messages,
                "llm_sql_ms",
                timings,
                tools=[EXECUTE_SQL_TOOL],
            ).message

            calls = reply.tool_calls or []

            # ==========================================================
            # CASE 1: Native tool calling
            # ==========================================================

            if calls:

                call = calls[0]

                args = dict(
                    call.function.arguments or {}
                )

                # Preserve the assistant tool-call message
                messages.append(
                    {
                        "role": "assistant",
                        "content": reply.content or "",
                        "tool_calls": [
                            {
                                "function": {
                                    "name": call.function.name,
                                    "arguments": args,
                                }
                            }
                        ],
                    }
                )

                if call.function.name != "execute_sql":

                    result = ToolResult(
                        success=False,
                        error=(
                            f"Unknown tool "
                            f"'{call.function.name}'"
                        ),
                        error_type="validation",
                    )

                else:

                    result = execute_sql(
                        str(args.get("sql", ""))
                    )

                timings["sql_exec_ms"] += (
                    result.elapsed_ms
                )

            # ==========================================================
            # CASE 2: Local model returned SQL as plain text
            #
            # Example:
            #
            # SQL: SELECT ...
            #
            # Qwen sometimes does this instead of using native
            # function calling.
            # ==========================================================

            else:

                recovered_sql = extract_sql_from_text(
                    reply.content or ""
                )

                if recovered_sql:

                    log.info(
                        "Recovered SQL from model text: %s",
                        recovered_sql,
                    )

                    # Preserve the original model response
                    messages.append(
                        {
                            "role": "assistant",
                            "content": reply.content or "",
                        }
                    )

                    # Send recovered SQL through the SAME
                    # validation + execution pipeline.
                    result = execute_sql(
                        recovered_sql
                    )

                    timings["sql_exec_ms"] += (
                        result.elapsed_ms
                    )

                else:

                    # The model did not provide SQL and did not
                    # produce a native tool call.
                    return AnalystResponse(
                        answer=(
                            reply.content or ""
                        ).strip()
                        or "Could you rephrase your question?",
                        status="clarification",
                        requires_clarification=True,
                        sources=ctx.sources,
                        sql_attempts=attempts - 1,
                    )

            # ==========================================================
            # SQL succeeded
            # ==========================================================

            if result.success:
                break

            # ==========================================================
            # SQL failed
            #
            # Tell the LLM what went wrong and allow one retry.
            # ==========================================================

            messages.append(
                {
                    "role": "tool",
                    "tool_name": "execute_sql",
                    "content": (
                        f"ERROR "
                        f"({result.error_type}): "
                        f"{result.error}\n"
                        "Fix the problem and call "
                        "execute_sql again with ONE "
                        "corrected read-only SELECT query. "
                        "Do not invent columns."
                    ),
                }
            )

        # ------------------------------------------------------------------
        # No successful SQL result
        # ------------------------------------------------------------------

        if result is None or not result.success:

            return AnalystResponse(
                answer=(
                    "I couldn't produce a valid, safe "
                    "query for that question. Try "
                    "rephrasing it or being more specific "
                    "about the metric and time period."
                ),
                status="failed",
                error=(
                    result.error
                    if result
                    else "no tool call"
                ),
                sources=ctx.sources,
                sql_attempts=attempts,
            )

        # ------------------------------------------------------------------
        # Step 2:
        #
        # Database result -> AUTHORITATIVE block
        # -> LLM interpretation
        #
        # IMPORTANT:
        # The database result is now the source of truth.
        # ------------------------------------------------------------------

        grounded = ground_result(
            result.columns,
            result.rows,
            db_truncated=result.truncated,
            max_rows_for_llm=s.llm_max_rows,
        )

        messages.append(
            {
                "role": "tool",
                "tool_name": "execute_sql",
                "content": grounded.text,
            }
        )

        messages.append(
            {
                "role": "user",
                "content": INTERPRET_INSTRUCTIONS,
            }
        )

        # ------------------------------------------------------------------
        # Generate and verify final answer
        # ------------------------------------------------------------------

        (
            llm_answer,
            grounding_status,
            repairs,
        ) = self._interpret(
            messages,
            grounded,
            question,
            timings,
        )

        # ------------------------------------------------------------------
        # Return final response
        #
        # SQL ALWAYS comes from Python's ToolResult.
        # Never from the LLM's final answer.
        # ------------------------------------------------------------------

        return AnalystResponse(
            answer=llm_answer.answer,

            # Exact SQL that passed validation/execution
            sql=result.sql,

            executed=True,

            confidence=llm_answer.confidence,

            reasoning_summary=(
                llm_answer.reasoning_summary
            ),

            data_used=llm_answer.data_used,

            requires_clarification=False,

            status="success",

            grounding_status=grounding_status,

            columns=result.columns,

            rows=result.rows,

            row_count=result.row_count,

            truncated=result.truncated,

            sources=ctx.sources,

            sql_attempts=attempts,

            answer_repairs=repairs,
        )

    # ------------------------------------------------------------------
    # Final answer generation
    # ------------------------------------------------------------------

    def _interpret(
        self,
        messages,
        grounded,
        question,
        timings,
    ):

        schema = LLMAnswer.model_json_schema()

        max_tries = (
            1 + self.settings.max_answer_repairs
        )

        for attempt in range(max_tries):

            raw = self._chat(
                messages,
                "llm_answer_ms",
                timings,
                format=schema,
            ).message.content or ""

            # ----------------------------------------------------------
            # Validate JSON/Pydantic structure
            # ----------------------------------------------------------

            try:

                parsed = LLMAnswer.model_validate_json(
                    raw
                )

            except ValidationError as exc:

                feedback = (
                    "Your output was not valid JSON "
                    "for the required schema: "
                    f"{exc.errors()[:2]}. "
                    "Return valid JSON."
                )

            else:

                # ------------------------------------------------------
                # Verify every numerical claim against
                # the authoritative database result.
                # ------------------------------------------------------

                check = verify_answer(
                    parsed.answer,
                    grounded,
                    question,
                )

                if check.ok:

                    return (
                        parsed,
                        (
                            "verified"
                            if attempt == 0
                            else "repaired"
                        ),
                        attempt,
                    )

                log.warning(
                    "Answer failed numeric verification: %s",
                    check.violations,
                )

                feedback = REPAIR_INSTRUCTIONS.format(
                    violations="\n".join(
                        f"- {v}"
                        for v in check.violations
                    )
                )

            # ----------------------------------------------------------
            # Give the model one opportunity to repair
            # ----------------------------------------------------------

            messages.append(
                {
                    "role": "assistant",
                    "content": raw,
                }
            )

            messages.append(
                {
                    "role": "user",
                    "content": feedback,
                }
            )

        # ------------------------------------------------------------------
        # Deterministic fallback
        #
        # If the LLM still cannot produce a verified answer,
        # Python generates the answer directly from the SQL result.
        # ------------------------------------------------------------------

        fallback = LLMAnswer(
            answer=grounded.fallback_answer,

            confidence=0.6,

            data_used=[],

            reasoning_summary=(
                "Wording generated directly from "
                "the query result because the model's "
                "answer could not be verified against it."
            ),
        )

        return (
            fallback,
            "fallback",
            max_tries - 1,
        )
